### PR TITLE
[JENKINS-23567] prevent logspam from distfork plugin.

### PR DESCRIPTION
**Pull request by jtnord**
@reviewbybees 
https://issues.jenkins-ci.org/browse/JENKINS-23567

### CODE REVIEW

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by stephenc** [comment]
:bee:

**Comment by tfennelly** [comment]
:bee:

**Comment by jtnord** [comment]
@reviewbybees done

**Comment by ghost** [comment]
This pull request has completed our internal processes and we now respectfully request the maintainers of this repository to consider our proposal contained within this pull request for merging.

**Pull request merged**
